return {
    {
        "nvim-treesitter/nvim-treesitter",
        opts = {
            ensure_installed = {
                "bash",
                "html",
                "svelte",
                "css",
                "javascript",
                "json",
                "lua",
                "markdown",
                "markdown_inline",
                "python",
                "regex",
                "tsx",
                "typescript",
                "vim",
                "yaml",
                "go",
                "gomod",
                "gosum",
                "gowork",
                "kotlin",
                "graphql",
            },
        },
    },
}
